name: 'Build and Push Frontend'
description: 'Build the frontend docker image and push the image to GCR'
inputs:
  dockerfile:
    description: 'Relative path to dockerfile'
    required: true
  image-path:
    description: 'Location to where image should be pushed'
    required: true
  data-server-url:
    description: 'Url to use for the data server'
    required: true
  deploy-context:
    description: 'String value for deploy context. Should be "prod" or "staging"'
    required: true
  disable-basic-auth:
    description: 'Whether to disable basic authentication. Defaults to false'
    required: false
  basic-auth-username:
    description: 'Username for basic authentication. Required if disable-basic-auth is false'
    required: false
  basic-auth-password:
    description: 'Password for basic authentication. Required if disable-basic-auth is false'
    required: false
outputs:	
    image-digest:	
      description: 'Digest of image pushed to GCR'	
      value: ${{ steps.get-image-digest.outputs.image-digest }}
runs:
  using: "composite"
  steps:
    - name: Set Up Docker to Use gcloud Credentials
      run: gcloud auth configure-docker -q
      shell: bash
    - run: |
        docker build -t ${{ inputs.image-path }} -f ${{ inputs.dockerfile }} . \
        --build-arg="NODE_ENV=production" \
        --build-arg="DATA_SERVER_URL=${{ inputs.data-server-url }}" \
        --build-arg="REACT_APP_DEPLOY_CONTEXT=${{ inputs.deploy-context }}" \
        --build-arg="DEPLOY_CONTEXT=${{ inputs.deploy-context }}" \
        --build-arg="DISABLE_BASIC_AUTH=${{ inputs.disable-basic-auth }}" \
        --build-arg="BASIC_AUTH_USERNAME=${{ inputs.basic-auth-username }}" \
        --build-arg="BASIC_AUTH_PASSWORD=${{ inputs.basic-auth-password }}"
      shell: bash
    - run: docker push ${{ inputs.image-path }}
      shell: bash
    - id: get-image-digest
      run: echo "::set-output name=image-digest::$(gcloud container images describe ${{ inputs.image-path }} --format='value(image_summary.digest)')"	
      shell: bash
