// Source: tokens/*.tokens.json
// Output: src/styles/tokens/{colors,typography,dimensions}.{css,ts}
// Run:    npm run tokens   (auto-runs on install / predev / prebuild)
import type { Config, Plugin } from '@terrazzo/parser'

interface Token {
  id: string
  $type: string
  $value: unknown
}

type BuildCtx = {
  tokens: Record<string, Token>
  outputFile: (filename: string, contents: string) => void
}

// ─── ID transformations ──────────────────────────────────────────────────────

const toKebab = (str: string) => str.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
const idToCssVar = (id: string) => '--' + id.split('.').map(toKebab).join('-')
const idToLeafKey = (id: string) => id.split('.').at(-1) ?? id
const idToCamelKey = (id: string) => {
  const [head, ...tail] = id.split('.')
  return head + tail.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
}

// ─── Token filters ───────────────────────────────────────────────────────────

const isColor = (t: Token) => t.id.startsWith('color.')
const isTypo = (t: Token) =>
  t.id.startsWith('font.') || t.id.startsWith('text.') || t.id.startsWith('leading.')
const isDim = (t: Token) => !isColor(t) && !isTypo(t)
const isBreakpoint = (t: Token) => t.id.startsWith('breakpoint.')

// ─── Helpers ─────────────────────────────────────────────────────────────────

const valueToString = (value: unknown): string =>
  Array.isArray(value) ? value.join(', ') : String(value)

const cssHeader = (src: string) =>
  `/* DO NOT EDIT — generated by Terrazzo from tokens/${src}.tokens.json */\n/* Run \`npm run tokens\` to regenerate. */\n`

const tsHeader = (src: string) =>
  `// DO NOT EDIT — generated by Terrazzo from tokens/${src}.tokens.json\n// Run \`npm run tokens\` to regenerate.\n`

// ─── Output builders ─────────────────────────────────────────────────────────

/**
 * Single @theme block: registers tokens with Tailwind for utility class generation.
 * Tailwind emits CSS var definitions to :root for tokens whose utility classes
 * (bg-*, text-*, font-*, etc.) appear in scanned content.
 *
 * All JS/TS consumers use the *Values exports (raw hex/strings) directly — no
 * CSS vars needed in application code.
 *
 * Dimensions use plain @theme so Tailwind embeds literal px values into @media
 * queries — var() in media queries is invalid CSS and silently breaks breakpoints.
 */
function makeCssOutput(
  tokens: Token[],
  srcName: string,
  { cssReset }: { cssReset?: string } = {},
) {
  const themeVars = tokens.map((t) => `  ${idToCssVar(t.id)}: ${valueToString(t.$value)};`).join('\n')
  const resetLine = cssReset ? `  ${cssReset}: initial;\n\n` : ''

  return `${cssHeader(srcName)}
@theme {
${resetLine}${themeVars}
}
`
}

function makeTsOutput(
  tokens: Token[],
  srcName: string,
  {
    keyFn,
    exportBase,
    extra = '',
  }: {
    keyFn: (id: string) => string
    exportBase: string
    extra?: string
  },
) {
  const valEntries = tokens
    .map((t) => `  ${keyFn(t.id)}: ${JSON.stringify(valueToString(t.$value))}`)
    .join(',\n')
  const ExportBase = exportBase.charAt(0).toUpperCase() + exportBase.slice(1)

  return `${tsHeader(srcName)}
export const ${exportBase}Values = {
${valEntries},
} as const

export type ${ExportBase}Key = keyof typeof ${exportBase}Values
${extra}`
}

// ─── Plugin factories ─────────────────────────────────────────────────────────

function cssPlugin(
  srcName: string,
  filter: (t: Token) => boolean,
  opts: { cssReset?: string } = {},
): Plugin {
  return {
    name: `${srcName}-css`,
    async build({ tokens, outputFile }: BuildCtx) {
      outputFile(
        `${srcName}.css`,
        makeCssOutput(Object.values(tokens).filter(filter), srcName, opts),
      )
    },
  }
}

function tsPlugin(
  srcName: string,
  filter: (t: Token) => boolean,
  opts: {
    keyFn: (id: string) => string
    exportBase: string
    extra?: (tokens: Token[]) => string
  },
): Plugin {
  return {
    name: `${srcName}-ts`,
    async build({ tokens, outputFile }: BuildCtx) {
      const filtered = Object.values(tokens).filter(filter)
      outputFile(
        `${srcName}.ts`,
        makeTsOutput(filtered, srcName, {
          ...opts,
          extra: opts.extra?.(filtered) ?? '',
        }),
      )
    },
  }
}

// ─── Config ───────────────────────────────────────────────────────────────────

export default {
  tokens: [
    './tokens/colors.tokens.json',
    './tokens/typography.tokens.json',
    './tokens/dimensions.tokens.json',
  ],
  outDir: './src/styles/tokens/',
  plugins: [
    cssPlugin('colors', isColor, { cssReset: '--color-*' }),
    tsPlugin('colors', isColor, { keyFn: idToLeafKey, exportBase: 'color' }),

    cssPlugin('typography', isTypo),
    tsPlugin('typography', isTypo, { keyFn: idToCamelKey, exportBase: 'typography' }),

    cssPlugin('dimensions', isDim),
    tsPlugin('dimensions', isDim, {
      keyFn: idToCamelKey,
      exportBase: 'dimension',
      extra: (tokens) => {
        const bpEntries = tokens
          .filter(isBreakpoint)
          .map((t) => `  ${idToLeafKey(t.id)}: '${valueToString(t.$value)}'`)
          .join(',\n')
        return `
export const breakpointValues = {
${bpEntries},
} as const

export type Breakpoint = keyof typeof breakpointValues
`
      },
    }),
  ],
} satisfies Config
