// @ts-check
// Source: tokens/*.tokens.json
// Output: src/styles/tokens/{colors,typography,dimensions}.{css,ts}
// Run:    npm run tokens   (auto-runs on install / predev / prebuild)

/** @typedef {{ id: string, $type: string, $value: unknown }} TerrazzoToken */

/** @param {string} str @returns {string} */
function toKebab(str) {
  return str.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

/** @param {string} id @returns {string} */
function idToCssVar(id) {
  return '--' + id.split('.').map(toKebab).join('-')
}

/** @param {string} id @returns {string} */
function idToLeafKey(id) {
  return id.split('.').at(-1) ?? id
}

/** @param {string} id @returns {string} */
function idToCamelKey(id) {
  const [head, ...tail] = id.split('.')
  return head + tail.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
}

/** @param {TerrazzoToken} t @returns {boolean} */
const isColor = (t) => t.id.startsWith('color.')

/** @param {TerrazzoToken} t @returns {boolean} */
const isTypo = (t) =>
  t.id.startsWith('font.') || t.id.startsWith('text.') || t.id.startsWith('leading.')

/** @param {TerrazzoToken} t @returns {boolean} */
const isDim = (t) => !isColor(t) && !isTypo(t)

/** @param {TerrazzoToken} t @returns {boolean} */
const isBreakpoint = (t) => t.id.startsWith('breakpoint.')

/** @param {string} src @returns {string} */
const FILE_HEADER_CSS = (src) =>
  `/* DO NOT EDIT — generated by Terrazzo from tokens/${src}.tokens.json */\n/* Run \`npm run tokens\` to regenerate. */\n`

/** @param {string} src @returns {string} */
const FILE_HEADER_TS = (src) =>
  `// DO NOT EDIT — generated by Terrazzo from tokens/${src}.tokens.json\n// Run \`npm run tokens\` to regenerate.\n`

/**
 * Coerce any DTCG $value to a CSS/TS output string.
 * @param {unknown} value @returns {string}
 */
const valueToString = (value) => {
  if (Array.isArray(value)) return value.join(', ')
  return String(value)
}

/**
 * Builds the two-block CSS output shared by all three token CSS files.
 *
 * @layer base :root  — unconditionally emits CSS vars to the browser so that
 *   var(--token-name) resolves everywhere (JS strings, SVG attributes, D3).
 *   Without this block, Tailwind tree-shakes vars whose utility classes are
 *   never referenced in scanned content (e.g. chart colors set via colorVars.*).
 *
 * @theme / @theme inline  — registers vars with Tailwind for utility class
 *   generation. Use plain @theme for dimensions: Tailwind must see literal
 *   pixel values to emit correct @media queries — var() in media queries is
 *   invalid CSS and silently breaks responsive layouts.
 *
 * @param {{ tokens: TerrazzoToken[], cssReset?: string, filename: string, srcName: string, inlineTheme?: boolean }} options
 * @returns {{ filename: string, contents: string }}
 */
function makeCssOutput({ tokens, cssReset, filename, srcName, inlineTheme = true }) {
  const rootVars = tokens
    .map((t) => `    ${idToCssVar(t.id)}: ${valueToString(t.$value)};`)
    .join('\n')

  const themeVars = inlineTheme
    ? tokens
        .map((t) => `  ${idToCssVar(t.id)}: var(${idToCssVar(t.id)});`)
        .join('\n')
    : tokens.map((t) => `  ${idToCssVar(t.id)}: ${valueToString(t.$value)};`).join('\n')

  const themeDirective = inlineTheme ? '@theme inline' : '@theme'
  const resetLine = cssReset ? `  ${cssReset}: initial;\n\n` : ''

  return {
    filename,
    contents: `${FILE_HEADER_CSS(srcName)}
@layer base {
  :root {
${rootVars}
  }
}

${themeDirective} {
${resetLine}${themeVars}
}
`,
  }
}

/**
 * Builds a TS file with two parallel exports:
 *   {type}Values  — raw token values (hex for colors, CSS strings for others)
 *   {type}Vars    — CSS var references for use in TypeScript component styles
 *
 * @param {{ tokens: TerrazzoToken[], keyFn: (id: string) => string, exportBase: string, filename: string, srcName: string, extra?: string }} options
 * @returns {{ filename: string, contents: string }}
 */
function makeTsOutput({ tokens, keyFn, exportBase, filename, srcName, extra = '' }) {
  const valEntries = tokens
    .map((t) => `  ${keyFn(t.id)}: ${JSON.stringify(valueToString(t.$value))}`)
    .join(',\n')

  const varEntries = tokens
    .map((t) => `  ${keyFn(t.id)}: 'var(${idToCssVar(t.id)})'`)
    .join(',\n')

  const ExportBase = exportBase.charAt(0).toUpperCase() + exportBase.slice(1)
  const Values = `${exportBase}Values`
  const Vars = `${exportBase}Vars`

  return {
    filename,
    contents: `${FILE_HEADER_TS(srcName)}
export const ${Values} = {
${valEntries},
} as const

export type ${ExportBase}Key = keyof typeof ${Values}

export const ${Vars} = {
${varEntries},
} as const
${extra}`,
  }
}

// ─── Colors ──────────────────────────────────────────────────────────────────

function colorsCssPlugin() {
  return {
    name: 'het-colors-css',
    /** @param {{ tokens: Record<string, TerrazzoToken>, outputFile: (filename: string, contents: string) => void }} ctx */
    async build({ tokens, outputFile }) {
      const { filename, contents } = makeCssOutput({
        tokens: Object.values(tokens).filter(isColor),
        cssReset: '--color-*',
        filename: 'colors.css',
        srcName: 'colors',
      })
      outputFile(filename, contents)
    },
  }
}

function colorsTsPlugin() {
  return {
    name: 'het-colors-ts',
    /** @param {{ tokens: Record<string, TerrazzoToken>, outputFile: (filename: string, contents: string) => void }} ctx */
    async build({ tokens, outputFile }) {
      const { filename, contents } = makeTsOutput({
        tokens: Object.values(tokens).filter(isColor),
        keyFn: idToLeafKey,
        exportBase: 'color',
        filename: 'colors.ts',
        srcName: 'colors',
      })
      outputFile(filename, contents)
    },
  }
}

// ─── Typography ──────────────────────────────────────────────────────────────

function typographyCssPlugin() {
  return {
    name: 'het-typography-css',
    /** @param {{ tokens: Record<string, TerrazzoToken>, outputFile: (filename: string, contents: string) => void }} ctx */
    async build({ tokens, outputFile }) {
      const { filename, contents } = makeCssOutput({
        tokens: Object.values(tokens).filter(isTypo),
        filename: 'typography.css',
        srcName: 'typography',
      })
      outputFile(filename, contents)
    },
  }
}

function typographyTsPlugin() {
  return {
    name: 'het-typography-ts',
    /** @param {{ tokens: Record<string, TerrazzoToken>, outputFile: (filename: string, contents: string) => void }} ctx */
    async build({ tokens, outputFile }) {
      const { filename, contents } = makeTsOutput({
        tokens: Object.values(tokens).filter(isTypo),
        keyFn: idToCamelKey,
        exportBase: 'typography',
        filename: 'typography.ts',
        srcName: 'typography',
      })
      outputFile(filename, contents)
    },
  }
}

// ─── Dimensions ──────────────────────────────────────────────────────────────

function dimensionsCssPlugin() {
  return {
    name: 'het-dimensions-css',
    /** @param {{ tokens: Record<string, TerrazzoToken>, outputFile: (filename: string, contents: string) => void }} ctx */
    async build({ tokens, outputFile }) {
      const { filename, contents } = makeCssOutput({
        tokens: Object.values(tokens).filter(isDim),
        filename: 'dimensions.css',
        srcName: 'dimensions',
        // Must NOT use @theme inline — Tailwind needs literal breakpoint values to
        // emit @media (min-width: 600px) queries. var() in media queries is invalid CSS.
        inlineTheme: false,
      })
      outputFile(filename, contents)
    },
  }
}

function dimensionsTsPlugin() {
  return {
    name: 'het-dimensions-ts',
    /** @param {{ tokens: Record<string, TerrazzoToken>, outputFile: (filename: string, contents: string) => void }} ctx */
    async build({ tokens, outputFile }) {
      const dimTokens = Object.values(tokens).filter(isDim)
      const bpTokens = dimTokens.filter(isBreakpoint)

      const bpEntries = bpTokens
        .map((t) => `  ${idToLeafKey(t.id)}: '${valueToString(t.$value)}'`)
        .join(',\n')

      const extra = `
export const breakpointValues = {
${bpEntries},
} as const

export type Breakpoint = keyof typeof breakpointValues
`
      const { filename, contents } = makeTsOutput({
        tokens: dimTokens,
        keyFn: idToCamelKey,
        exportBase: 'dimension',
        filename: 'dimensions.ts',
        srcName: 'dimensions',
        extra,
      })
      outputFile(filename, contents)
    },
  }
}

// ─── Config ──────────────────────────────────────────────────────────────────

/** @type {import("@terrazzo/parser").Config} */
export default {
  tokens: [
    './tokens/colors.tokens.json',
    './tokens/typography.tokens.json',
    './tokens/dimensions.tokens.json',
  ],
  outDir: './src/styles/tokens/',
  plugins: [
    colorsCssPlugin(),
    colorsTsPlugin(),
    typographyCssPlugin(),
    typographyTsPlugin(),
    dimensionsCssPlugin(),
    dimensionsTsPlugin(),
  ],
}
