// @ts-check
// DO NOT EDIT output files — edit tokens/*.tokens.json and run `npm run tokens`

/** camelCase or dotted.camelCase segment → kebab-case */
function toKebab(str) {
  return str.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

/** token.id like "color.altGreen" → "--color-alt-green" */
function idToCssVar(id) {
  return '--' + id.split('.').map(toKebab).join('-')
}

/** Generates colorValues.ts — hetColors hex export + HetColorKey type */
function hetColorsPlugin() {
  return {
    name: 'het-colors-ts',
    async build({ tokens }) {
      const colors = tokens.filter((t) => t.$type === 'color')
      const entries = colors
        .map((t) => {
          const key = t.id.split('.').at(-1)
          return `  ${key}: '${t.$value}'`
        })
        .join(',\n')

      const contents = `// DO NOT EDIT — generated by Cobalt from tokens/colors.tokens.json
// Run \`npm run tokens\` to regenerate.
export const hetColors = {
${entries},
} as const

export type HetColorKey = keyof typeof hetColors
`
      return [{ filename: 'colorValues.ts', contents }]
    },
  }
}

/** Generates colorVars.css
 *
 * Two-block approach required by Tailwind v4:
 *
 * 1. @layer base :root — emits CSS var definitions unconditionally so that
 *    var(--color-*) references in JavaScript / SVG attributes always resolve.
 *    (Tailwind tree-shakes @theme definitions for vars whose utility classes
 *    are never used in scanned content — chart colors used only via het.* JS
 *    strings would silently disappear without this block.)
 *
 * 2. @theme inline — registers each color with Tailwind using a var() reference
 *    so utility classes (bg-*, text-*, border-*, etc.) are generated and point
 *    to the :root var rather than inlining the hex value.
 */
function hetColorsCssPlugin() {
  return {
    name: 'het-colors-css',
    async build({ tokens }) {
      const colors = tokens.filter((t) => t.$type === 'color')

      const rootVars = colors
        .map((t) => `    ${idToCssVar(t.id)}: ${t.$value};`)
        .join('\n')

      const themeVars = colors
        .map((t) => `  ${idToCssVar(t.id)}: var(${idToCssVar(t.id)});`)
        .join('\n')

      const contents = `/* DO NOT EDIT — generated by Cobalt from tokens/colors.tokens.json */
/* Run \`npm run tokens\` to regenerate. */

/* Always emit CSS vars to :root so var(--color-*) works in JS/SVG/D3 */
@layer base {
  :root {
${rootVars}
  }
}

/* Register colors with Tailwind for utility class generation */
@theme inline {
  /* disable Tailwind built-in colors */
  --color-*: initial;

${themeVars}
}
`
      return [{ filename: 'colorVars.css', contents }]
    },
  }
}

/** Generates colorVars.ts — het CSS-var-string export + HetColor type */
function hetVarsPlugin() {
  return {
    name: 'het-vars-ts',
    async build({ tokens }) {
      const colors = tokens.filter((t) => t.$type === 'color')
      const entries = colors
        .map((t) => {
          const key = t.id.split('.').at(-1)
          const cssVar = idToCssVar(t.id)
          return `  ${key}: 'var(${cssVar})'`
        })
        .join(',\n')

      const contents = `// DO NOT EDIT — generated by Cobalt from tokens/colors.tokens.json
// Run \`npm run tokens\` to regenerate.
export const het = {
${entries},
} as const

export type HetColor = (typeof het)[keyof typeof het]
`
      return [{ filename: 'colorVars.ts', contents }]
    },
  }
}

/** Generates designTokens.css — Tailwind v4 @theme block for typography + dimensions */
function designTokensCssPlugin() {
  return {
    name: 'het-design-tokens-css',
    async build({ tokens }) {
      const nonColors = tokens.filter((t) => t.$type !== 'color')
      const vars = nonColors
        .map((t) => `  ${idToCssVar(t.id)}: ${t.$value};`)
        .join('\n')

      const contents = `/* DO NOT EDIT — generated by Cobalt from tokens/typography.tokens.json + tokens/dimensions.tokens.json */
/* Run \`npm run tokens\` to regenerate. */
@theme {

${vars}

}
`
      return [{ filename: 'designTokens.css', contents }]
    },
  }
}

/** @type {import("@cobalt-ui/core").Config} */
export default {
  tokens: ['./tokens/colors.tokens.json', './tokens/typography.tokens.json', './tokens/dimensions.tokens.json'],
  outDir: './src/styles/theme/',
  plugins: [
    hetColorsPlugin(),
    hetColorsCssPlugin(),
    hetVarsPlugin(),
    designTokensCssPlugin(),
  ],
}
