// @ts-check
// Source: tokens/*.tokens.json
// Output: src/styles/tokens/{colors,typography,dimensions}.{css,ts}
// Run:    npm run tokens   (auto-runs on install / predev / prebuild)

/** camelCase segment → kebab-case */
function toKebab(str) {
  return str.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

/** 'color.altGreen' → '--color-alt-green' */
function idToCssVar(id) {
  return '--' + id.split('.').map(toKebab).join('-')
}

/** 'color.altGreen' → 'altGreen'  (leaf key, strips group prefix) */
function idToLeafKey(id) {
  return id.split('.').at(-1)
}

/** 'font.sansTitle' → 'fontSansTitle'  (full prefixed camelCase) */
function idToCamelKey(id) {
  const [head, ...tail] = id.split('.')
  return head + tail.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
}

const isColor = (t) => t.$type === 'color'
const isTypo = (t) =>
  t.id.startsWith('font.') || t.id.startsWith('text.') || t.id.startsWith('leading.')
const isDim = (t) => !isColor(t) && !isTypo(t)
const isBreakpoint = (t) => t.id.startsWith('breakpoint.')

const FILE_HEADER_CSS = (src) =>
  `/* DO NOT EDIT — generated by Cobalt from tokens/${src}.tokens.json */\n/* Run \`npm run tokens\` to regenerate. */\n`
const FILE_HEADER_TS = (src) =>
  `// DO NOT EDIT — generated by Cobalt from tokens/${src}.tokens.json\n// Run \`npm run tokens\` to regenerate.\n`

/**
 * Builds the two-block CSS output shared by all three token CSS files.
 *
 * @layer base :root  — unconditionally emits CSS vars to the browser so that
 *   var(--token-name) resolves everywhere (JS strings, SVG attributes, D3).
 *   Without this block, Tailwind tree-shakes vars whose utility classes are
 *   never referenced in scanned content (e.g. chart colors set via het.*).
 *
 * @theme inline  — registers the same vars with Tailwind using var() references
 *   so utility classes (bg-*, text-*, rounded-*, etc.) are generated and point
 *   to the :root vars rather than inlining the raw values.
 */
/**
 * @param {boolean} [inlineTheme=true]
 *   true  → @theme inline (utilities reference CSS vars via var())
 *   false → @theme         (utilities inline literal values — REQUIRED for
 *           breakpoint tokens because CSS media queries cannot use var())
 */
function makeCssOutput({ tokens, cssReset, filename, srcName, inlineTheme = true }) {
  const rootVars = tokens
    .map((t) => `    ${idToCssVar(t.id)}: ${t.$value};`)
    .join('\n')

  const themeVars = inlineTheme
    ? tokens.map((t) => `  ${idToCssVar(t.id)}: var(${idToCssVar(t.id)});`).join('\n')
    : tokens.map((t) => `  ${idToCssVar(t.id)}: ${t.$value};`).join('\n')

  const themeDirective = inlineTheme ? '@theme inline' : '@theme'
  const resetLine = cssReset ? `  ${cssReset}: initial;\n\n` : ''

  return {
    filename,
    contents: `${FILE_HEADER_CSS(srcName)}
@layer base {
  :root {
${rootVars}
  }
}

${themeDirective} {
${resetLine}${themeVars}
}
`,
  }
}

/**
 * Builds a TS file with two parallel exports:
 *   {type}Values  — raw token values (hex for colors, CSS strings for others)
 *   {type}Vars    — CSS var references for use in TypeScript component styles
 * Plus a type alias.
 */
function makeTsOutput({ tokens, keyFn, exportBase, filename, srcName, extra = '' }) {
  const valEntries = tokens
    .map((t) => `  ${keyFn(t.id)}: '${t.$value.replace(/'/g, "\\'")}'`)
    .join(',\n')

  const varEntries = tokens
    .map((t) => `  ${keyFn(t.id)}: 'var(${idToCssVar(t.id)})'`)
    .join(',\n')

  const Values = `${exportBase}Values`
  const Vars = `${exportBase}Vars`

  return {
    filename,
    contents: `${FILE_HEADER_TS(srcName)}
export const ${Values} = {
${valEntries},
} as const

export type ${
      exportBase.charAt(0).toUpperCase() + exportBase.slice(1)
    }Key = keyof typeof ${Values}

export const ${Vars} = {
${varEntries},
} as const
${extra}`,
  }
}

// ─── Colors ──────────────────────────────────────────────────────────────────

function colorsCssPlugin() {
  return {
    name: 'het-colors-css',
    async build({ tokens }) {
      return [
        makeCssOutput({
          tokens: tokens.filter(isColor),
          cssReset: '--color-*',
          filename: 'colors.css',
          srcName: 'colors',
        }),
      ]
    },
  }
}

function colorsTsPlugin() {
  return {
    name: 'het-colors-ts',
    async build({ tokens }) {
      return [
        makeTsOutput({
          tokens: tokens.filter(isColor),
          keyFn: idToLeafKey,
          exportBase: 'color',
          filename: 'colors.ts',
          srcName: 'colors',
        }),
      ]
    },
  }
}

// ─── Typography ──────────────────────────────────────────────────────────────

function typographyCssPlugin() {
  return {
    name: 'het-typography-css',
    async build({ tokens }) {
      return [
        makeCssOutput({
          tokens: tokens.filter(isTypo),
          filename: 'typography.css',
          srcName: 'typography',
        }),
      ]
    },
  }
}

function typographyTsPlugin() {
  return {
    name: 'het-typography-ts',
    async build({ tokens }) {
      return [
        makeTsOutput({
          tokens: tokens.filter(isTypo),
          keyFn: idToCamelKey,
          exportBase: 'typography',
          filename: 'typography.ts',
          srcName: 'typography',
        }),
      ]
    },
  }
}

// ─── Dimensions ──────────────────────────────────────────────────────────────

function dimensionsCssPlugin() {
  return {
    name: 'het-dimensions-css',
    async build({ tokens }) {
      return [
        makeCssOutput({
          tokens: tokens.filter(isDim),
          filename: 'dimensions.css',
          srcName: 'dimensions',
          // Must NOT use inline — Tailwind needs literal breakpoint values to
          // emit @media (min-width: 600px) queries. var() in media queries is invalid CSS.
          inlineTheme: false,
        }),
      ]
    },
  }
}

function dimensionsTsPlugin() {
  return {
    name: 'het-dimensions-ts',
    async build({ tokens }) {
      const dimTokens = tokens.filter(isDim)
      const bpTokens = dimTokens.filter(isBreakpoint)

      // breakpointValues is a flat leaf-keyed map used by useIsBreakpointAndUp
      const bpEntries = bpTokens
        .map((t) => `  ${idToLeafKey(t.id)}: '${t.$value}'`)
        .join(',\n')

      const extra = `
export const breakpointValues = {
${bpEntries},
} as const

export type Breakpoint = keyof typeof breakpointValues
`
      return [
        makeTsOutput({
          tokens: dimTokens,
          keyFn: idToCamelKey,
          exportBase: 'dimension',
          filename: 'dimensions.ts',
          srcName: 'dimensions',
          extra,
        }),
      ]
    },
  }
}

// ─── Config ──────────────────────────────────────────────────────────────────

/** @type {import("@cobalt-ui/core").Config} */
export default {
  tokens: [
    './tokens/colors.tokens.json',
    './tokens/typography.tokens.json',
    './tokens/dimensions.tokens.json',
  ],
  outDir: './src/styles/tokens/',
  plugins: [
    colorsCssPlugin(),
    colorsTsPlugin(),
    typographyCssPlugin(),
    typographyTsPlugin(),
    dimensionsCssPlugin(),
    dimensionsTsPlugin(),
  ],
}
