const ThemeStandardScreenSizes = {
  xs: '0px',
  tiny: '350px',
  sm: '600px',
  smplus: '768px',
  md: '960px',
  lg: '1280px',
  lgplus: '1440px',
  xl: '1920px',
  full: '100%',
  eighty: '80vw',
}

const ThemeLineHeights = {
  loose: '1.6',
  'some-more-space': '1.3',
  'some-space': '1.15',
  normal: '1',
  tight: '0.95',
  'modal-heading': '1.25',
  'list-box-title': '47px',
}

const ThemeZIndexValues = {
  /*
          NOTE: some z indexes are generated by npm packages
          multimap modal blur backdrop: -1
          MUI sticky headers assigned: 2
          joyride warm welcome auto-assigned: 101
          */
  bottom: -999,
  middle: 0,
  almostTop: 3,
  mapTooltip: 98,
  top: 99,
  stickyMadLib: 100,
  multimapModal: 101,
  skipLink: 102,
  multimapModalTooltip: 1300,
}

const ThemeFonts = {
  // Nested quotations are required for font names with spaces
  sansTitle: ["'DM Sans Variable'", 'sans-serif'],
  sansText: ['"Inter Variable"', 'sans-serif'],
  roboto: ['Roboto', 'sans-serif'],
  robotoCondensed: ["'Roboto Condensed'", 'sans-serif'],
  serif: ['Taviraj', 'serif'],
}

const ThemeFontSizes = {
  'tiny-tag': '0.625rem',
  smallest: '0.75rem',
  small: '0.875rem',
  text: '1rem',
  title: '1.125rem',
  'explore-button': '1.2rem',
  'nav-bar-header': '1.25rem',
  'fluid-mad-lib': 'clamp(1rem, 2.5vw, 1.5rem)',
  'smallest-header': '1.5rem',
  'small-header': '1.75rem',
  header: '2rem',
  'big-header': '3rem',
  'bigger-header': '3.125rem',
  'hero-header': '4.5rem',
}

const ThemeBorderRadii = {
  xs: '2px',
  sm: '4px',
  md: '8px',
  lg: '16px',
  xl: '30px',
  '2xl': '40px',
  '3xl': '64px',
}

const ThemeBoxShadows = {
  raised:
    'rgba(0, 0, 0, 0.2) 0px 5px 5px -3px, rgba(0, 0, 0, 0.14) 0px 8px 10px 1px, rgba(0, 0, 0, 0.12) 0px 3px 14px 2px',
  'raised-tighter':
    'rgba(0, 0, 0, 0.1) 0px 3px 3px -2px, rgba(0, 0, 0, 0.08) 0px 6px 7px 0px, rgba(0, 0, 0, 0.06) 0px 2px 9px 1px',
}

const het = {
  alertColor: '#d85c47',
  altGreen: '#0b5240',
  barChartLight: '#91c684',
  black: '#000',
  borderColor: '#3e3e3e',
  darkGreen: '#083f31',
  howToColor: '#bdc1c6',

  mapDarkZero: '#35403d',
  mapDark: '#027e47',
  mapDarker: '#185e49',
  mapDarkest: '#134b3a',
  mapLightZero: '#fff9c1',
  mapLight: '#7db640',
  mapLighter: '#b9ce3a',
  mapLightest: '#f2e62f',
  mapMid: '#3e9b42',

  mapMedicareDarkZero: '#090121',
  mapMedicareDarkest: '#46327f',
  mapMedicareDark: '#365c8d',
  mapMedicareMid: '#267f8e',
  mapMedicareLight: '#1fa187',
  mapMedicareLighter: '#4bc16c',
  mapMedicareEvenLighter: '#9fda3a',
  mapMedicareLightest: '#f0e525',
  mapMedicareLightZero: '#fff9c1',

  mapMenLightest: '#fbc127',
  mapMenLighter: '#f57d15',
  mapMenLight: '#d44843',
  mapMenMid: '#9f2a63',
  mapMenDark: '#65156e',
  mapMenDarker: '#280b54',

  mapWomenDarkZero: '#120161',
  mapWomenDark: '#8b0aa5',
  mapWomenDarker: '#5402a3',
  mapWomenDarkest: '#320161',
  mapWomenLightZero: '#f3e221',
  mapWomenLight: '#db5b68',
  mapWomenLighter: '#f48849',
  mapWomenLightest: '#febc2b',
  mapWomenMid: '#b93389',

  mapYouthDarkZero: '#5a2f2a',
  mapYouthDarkest: '#772f2a',
  mapYouthDarker: '#a33a2b',
  mapYouthDark: '#c34e27',
  mapYouthMid: '#e06226',
  mapYouthLight: '#e87b26',
  mapYouthLighter: '#f09726',
  mapYouthLightest: '#f4b02a',
  mapYouthLightZero: '#f7d136',

  secondaryDark: '#167b6f',
  secondaryLight: '#89d5cc',
  secondaryMain: '#228b7e',

  standardInfo: '#f8f9fa',
  standardWarning: '#fff8eb',

  toggleColor: '#e1e9e7',
  unknownMapLeast: '#d3eece',
  unknownMapLesser: '#b8e3be',
  unknownMapLess: '#92d4be',
  unknownMapMid: '#60bccb',
  unknownMapMore: '#47a8cb',
  unknownMapMost: '#0b61a2',

  white: '#fff',
}

export {
  het,
  ThemeBorderRadii,
  ThemeBoxShadows,
  ThemeFontSizes,
  ThemeFonts,
  ThemeLineHeights,
  ThemeStandardScreenSizes,
  ThemeZIndexValues,
}
