gcs_landing_bucket        = "msm-test-landing-bucket"
gcs_manual_bucket         = "msm-test-manual-data-bucket"
manual_uploads_project_id = "het-infra-test-05"
bq_dataset_name           = "test_data_sources"
bq_manual_dataset_name    = "test_manual_data_sources"
export_bucket             = "het-data-tables"
