import React from "react";
import Grid from "@material-ui/core/Grid";
import Typography from "@material-ui/core/Typography";
import styles from "./AboutUsPage.module.scss";
import Button from "@material-ui/core/Button";
import { EXPLORE_DATA_PAGE_LINK } from "../../utils/urlutils";

/* TODO - Align with mocks, Clean up CSS */
function TrackerTab() {
  const OUR_JOURNEY = (
    <Grid container xs={12} className={styles.GreyGridItem}>
      <Grid
        container
        xs={12}
        justify="center"
        className={styles.Grid}
        spacing={5}
      >
        <Grid item xs={6}>
          <h1>Our journey</h1>
          <p>
            Started in 2020 during the COVID-19 pandemic,  the Health Equity
            Tracker aggregates up-to-date demographic data from communities that
            are  being hit hardest by the pandemic.
          </p>
          <p>
            The data will power the Health Equity Tracker that’ll give a
            detailed breakdown of the virus’s impact by race, ethnicity, gender,
            socioeconomic status, and other critical factors. This tracker will
            help policymakers better understand what resources and support
            affected communities need to close gaps and battle the virus
            effectively.
          </p>
        </Grid>
        <Grid item xs={6}>
          We’ve made great progress in creating this dashboard:
          <br />
          <br />
          <Grid container spacing={5} justify="center">
            <Grid item xs={6}>
              <span className={styles.UnderlinedHeader}>5 data sources</span>
              <p>
                {/* TODO - we could get the number of data sources dynamically from metadata so do don't forget to update this text*/}
                HET currently aggregates data from 5 key data sources. We plan
                to continue expanding data sources.
              </p>
            </Grid>
            <Grid item xs={6}>
              <span className={styles.UnderlinedHeader}>15 variables</span>
              <p>
                Covering COVID-19 cases deaths, and hospitalizations, COPD,
                asthma, diabetes, hypertension, obesity, SDOH, and more
              </p>
            </Grid>
            <Grid item xs={12}>
              <span className={styles.UnderlinedHeader}>
                Looking to the future
              </span>
              <p>
                HET will continue to expand its scale and scope to allow for
                more local drill-downs, and more comprehensive coverage of
                various health outcomes and determinants of health.
              </p>
            </Grid>
          </Grid>
          <a href={EXPLORE_DATA_PAGE_LINK}>
            <Button color="secondary" variant="contained">
              Explore the data
            </Button>
          </a>
        </Grid>
      </Grid>
    </Grid>
  );

  const OUR_VISION = (
    <Grid container xs={12}>
      <Grid item xs={4}>
        <img src="img/vision1.png" alt="Black Lives Matter protestors" />
        <b>Examining comprehensive determinants of health</b>
        <ul>
          <li>
            Analyze how local policies impact COVID-19 outcomes, resource
            allocation, and more
          </li>
          <li>
            Share research on racial, ethnic, and socioeconomic disparities
          </li>
          <li>
            Understand and share information on mental and behavioral health
            equity impact of COVID-19
          </li>
        </ul>
      </Grid>
      <Grid item xs={4}>
        <img src="img/vision2.png" alt="Capitol Hill Rotunda" />
        <b>Benchmarking equity to create impactful policies</b>
        <ul>
          <li>Create actionable policies in and with diverse communities</li>
          <li>
            Develop policy templates for local, state, and federal policy makers
          </li>
          <li>
            Develop and publish a health equity report card with the COVID-19
            Health Equity Commission (CHEC)
          </li>
        </ul>
      </Grid>
      <Grid item xs={4}>
        <img src="img/vision3.png" alt="A team working together" />
        <b>Empower policy influencers and makers to act now</b>
        <ul>
          <li>Engage with diverse communities across the country</li>
          <li>
            Coordinate COVID-19 community engagement, education, training,
            information exchange and dissemination, policy analysis, and
            advocacy
          </li>
        </ul>
      </Grid>
    </Grid>
  );

  const ETHICS_GRID = (
    <Grid container xs={12} spacing={5}>
      <Grid item xs={4}>
        <h4>Transparency & Accountability</h4>
        <p>
          We put transparency and accountability at the forefront by partnering
          closely with diverse communities, and by being transparent about who
          is interpreting data results generated by the Tracker and how this
          shapes the overall health narrative.
        </p>
      </Grid>
      <Grid item xs={4}>
        <h4>People Centered & Community Centric</h4>
        <p>
          Communities and their needs drive this work. The data powering the
          Tracker must accurately represent underserved populations and support
          their policy-change needs, through shared ownership.
        </p>
      </Grid>
      <Grid item xs={4}>
        <h4>Open Access & Participation</h4>
        <p>
          We ensure community leaders play an active role in helping to decide
          what data to use in developing policy recommendations.
        </p>
      </Grid>
    </Grid>
  );

  return (
    <>
      <Grid container justify="space-around" className={styles.Grid}>
        <Typography
          variant="h5"
          style={{ textAlign: "center", margin: "40px" }}
        >
          We aim to collect and centralize health inequity data from across the
          United States relating to race, ethnicity and socio-economic status,
          which includes information on comorbidities, COVID-19 deaths, hospital
          admissions, outcomes and more.
        </Typography>
        <h1>We are committed to the following ethics:</h1>
        {ETHICS_GRID}
        <Grid item xs={12}>
          <div style={{ width: "400px", textAlign: "center", margin: "auto" }}>
            <h1>
              With the launch of this resource, the HET will primarily focus on
              select social and political determinants of health as they relate
              to the COVID-19 pandemic.
            </h1>
            <h1>
              The data presented has been ethically sourced and curated from
              public-facing databases by our team of specialized researchers,
              data scientists and engineers.
            </h1>
          </div>
        </Grid>
        <span className={styles.UnderlinedHeader}>This tracker’s vision</span>
        {OUR_VISION}
      </Grid>
      {OUR_JOURNEY}
      <Grid container justify="space-around" className={styles.Grid}>
        <span className={styles.UnderlinedHeader}>See us in the press</span>
        <Grid container spacing={10}>
          {["1", "2", "3"].map((i) => (
            <Grid item xs={4}>
              <h1>2020 Year-in-Review</h1>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempo
              <br />
              <a href="/">Learn more</a>
            </Grid>
          ))}
        </Grid>
      </Grid>
    </>
  );
}

export default TrackerTab;
