import React from "react";
import styles from "./LandingPage.module.scss";
import Grid from "@material-ui/core/Grid";
import Typography from "@material-ui/core/Typography";
import Tabs from "@material-ui/core/Tabs";
import Tab from "@material-ui/core/Tab";

function AboutUsPage() {
  const [value, setValue] = React.useState(0);

  const handleChange = (event: React.ChangeEvent<{}>, newValue: number) => {
    setValue(newValue);
  };

  return (
    <div className={styles.LandingPage}>
      <Grid container justify="space-around" className={styles.Grid}>
        <Tabs
          value={value}
          onChange={handleChange}
          indicatorColor="primary"
          textColor="primary"
          centered
          style={{ marginTop: "40px" }}
        >
          <Tab label="The Tracker" />
          <Tab label="Our Team" />
          <Tab label="Frequently Asked Questions" />
          <Tab label="Contact Us" />
        </Tabs>
        <Typography variant="h5" style={{ textAlign: "center" }}>
          We aim to collect and centralize health inequity data from across the
          United States relating to race, ethnicity and socio-economic status,
          which includes information on comorbidities, COVID-19 deaths, hospital
          admissions, outcomes and more.
        </Typography>

        <h3>We are committed to the following ethics:</h3>
        <Grid container xs={12}>
          <Grid item xs={4}>
            <h4>Transparency & Accountability</h4>
            <p>
              Ensuring that accountability measures are in place honoring the
              proposition of "do no harm," fully involving local community
              representation, and being transparent about whose voice shapes the
              narrative about how to interpret data results generated by the
              Tracker
            </p>
          </Grid>
          <Grid item xs={4}>
            <h4>People Centered & Community Centric</h4>
            <p>
              Communities and their needs are centered and drive this work;
              ensuring shared ownership and that the data generated by the
              Tracker best represents those populations and priorities, and
              supports their policy-change needs in partnership with other
              stakeholders and allies.
            </p>
          </Grid>
          <Grid item xs={4}>
            <h4>Open Access & Participation</h4>
            <p>
              Ensuring that the communities' wisdom from which data sources
              derive are included in decision-making about what data to use in
              developing policy recommendations
            </p>
          </Grid>
        </Grid>

        <h3>
          With the launch of this resource, the HET will primarily focus on
          select social and political determinants of health as they relate to
          the COVID-19 pandemic.
        </h3>
        <h3>
          The data presented has been ethically sourced and curated from
          public-facing databases by our team of specialized researchers, data
          scientists and engineers.
        </h3>
        <h3>This tracker’s vision</h3>

        <Grid container xs={12}>
          <Grid item xs={4}>
            <img src="img/vision1.png" />
            Examining comprehensive determinants of health
            <ul>
              <li>
                Analyze how local policies impact COVID-19 outcomes, resource
                allocation, and more
              </li>
              <li>
                Share research on racial, ethnic, and socioeconomic disparities
              </li>
              <li>
                Understand and share information on mental and behavioral health
                equity impact of COVID-19
              </li>
            </ul>
          </Grid>
          <Grid item xs={4}>
            <img src="img/vision2.png" />
            Benchmarking equity to create impactful policies
            <ul>
              <li>
                Create actionable policies in and with diverse communities
              </li>
              <li>
                Develop policy templates for local, state, and federal policy
                makers
              </li>
              <li>
                Develop and publish a health equity report card with the
                COVID-19 Health Equity Commission (CHEC)
              </li>
            </ul>
          </Grid>
          <Grid item xs={4}>
            <img src="img/vision3.png" />
            Empower policy influencers and makers to act now
            <ul>
              <li>Engage with diverse communities across the country</li>
              <li>
                Coordinate COVID-19 community engagement, education, training,
                information exchange and dissemination, policy analysis, and
                advocacy
              </li>
            </ul>
          </Grid>
        </Grid>
        <Grid container xs={12}>
          <Grid item xs={6} style={{ background: "#F9F9F9" }}>
            <h5>Our journey</h5>
            <p>
              Founded in 2020 during the Coronavirus-19 pandemic, the Health
              Equity Tracker was created to enable the real-time COVID-19
              collection and study of detailed demographic data about the
              communities of color that are being hit hardest by the pandemic
            </p>
            <p>
              The ongoing research will build a database with a detailed
              breakdown of the virus’s impact by race, ethnicity, gender,
              socioeconomic status and other critical factors. The data, in
              turn, will help policymakers better understand how to ensure those
              communities receive the targeted help that they need to close
              those racial gaps and ensure the communities receive the resources
              and support that they need to battle the virus
            </p>
          </Grid>
          <Grid item xs={6}>
            We’ve made great progress in creating this dashboard:
            <Grid container>
              <Grid item xs={6}>
                <h6>5 databases</h6>
                <p>
                  We’re ingesting data from 5 key databases. We plan to expand
                  this to more in the coming years
                </p>
                <h6>10 built</h6>
                <p>
                  Covering COVID-19 cases deaths, and hospitalizations, COPD,
                  ashtma, diabetes, hypertension, obesity, and more{" "}
                </p>
              </Grid>
              <Grid item xs={6}>
                <h6>4 key indicators</h6>
                <p>Four major indicators are htawepthiapwehi iawephtaiweht</p>
                <h6>5 coming</h6>
                <p>
                  SDOH and PDOH variables that are coming include: crowding,
                  vulnerability indices, etih
                </p>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    </div>
  );
}

export default AboutUsPage;
