declare module 'dom-to-image-more'
declare module '@fontsource-variable/dm-sans'
declare module '@fontsource-variable/inter'
declare module '@fontsource/roboto'
declare module '@fontsource/roboto-condensed'
