#!/bin/bash

source .env.secrets

if [[ -z "$PROPUBLICA_API_KEY" ]]; then
    echo "Error. Must ensure /scripts/.env.secrets file exists and contains your PROPUBLICA_API_KEY. See /scripts/.env.secrets.example for more details." 1>&2
    exit 1
fi

echo "ProPublica API key found. Updating Congress (House + Senate) data...."

#HTTP Request
# GET https://api.propublica.org/congress/v1/{congress}/{chamber}/members.json

# Query Parameters
# Parameter	Description
# congress	102-117 for House, 80-117 for Senate
# chamber	house or senate

curl -H "X-API-Key: ${PROPUBLICA_API_KEY}" "https://api.propublica.org/congress/v1/117/senate/members.json" > ../data/cawp/propublica-us-senate.json

curl -H "X-API-Key: ${PROPUBLICA_API_KEY}" "https://api.propublica.org/congress/v1/117/house/members.json" > ../data/cawp/propublica-us-house.json


echo "Updated House and Senate files in /data/cawp"