name: "Build and Push"
description: "Build a docker image and push the image to GCR"
inputs:
  ahr-api-key: 
    description: "AHR API key used to fetch AHR data from the GraphQL endpoint"
    required: false
  dockerfile:
    description: "Relative path to dockerfile"
    required: true
  image-path:
    description: "Location to where image should be pushed"
    required: true
  build-directory:
    description: "Directory from where docker build should be run"
    required: false
    default: "."
  deploy-context:
    description: 'String value for deploy context. Should be "prod" or "staging". Only used for the frontend'
    required: false
  openai-api-key:
    description: "OpenAI API key for generating insights"
    required: false
outputs:
  image-digest:
    description: "Digest of image pushed to GCR"
    value: ${{ steps.get-image-digest.outputs.image-digest }}
runs:
  using: "composite"
  steps:
    - name: Set Up Docker to Use gcloud Credentials
      run: gcloud auth configure-docker -q
      shell: bash
    # Note: it is not generally recommended to pass secrets as build args, but
    # them to users for beta testing. If we ever need to rely on credentials for
    # protecting sensitive information, we should not use build args.
    # More info here: https://docs.docker.com/engine/reference/builder/#arg
    - run: |
        docker build -t ${{ inputs.image-path }} -f ${{ inputs.dockerfile }} ${{ inputs.build-directory }} \
        --build-arg="DEPLOY_CONTEXT=${{ inputs.deploy-context }}" \
        --build-arg="AHR_API_KEY=${{ inputs.ahr-api-key }}" \
        --build-arg="OPENAI_API_KEY=${{ inputs.openai-api-key }}"
      shell: bash
    - run: docker push ${{ inputs.image-path }}
      shell: bash
    - id: get-image-digest
      run: echo "image-digest=$(gcloud container images describe ${{ inputs.image-path }} --format='value(image_summary.digest)')" >> $GITHUB_OUTPUT
      shell: bash
