name: 'Build and Push'
description: 'Build a docker image and push the image to GCR'
inputs:
  dockerfile:
    description: 'Relative path to dockerfile'
    required: true
  image-path:
    description: 'Location to where image should be pushed'
    required: true
  service-account-key:
    description: 'GCP Service Account key'
    required: true
  project-id:
    description: 'GCP Project ID'
    required: true
outputs:	
    image-digest:	
      description: 'Digest of image pushed to GCR'	
      value: ${{ steps.get-image-digest.outputs.image-digest }}
runs:
  using: "composite"
  steps:
    - name: Set Up gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        export_default_credentials: true
        service_account_key: ${{ inputs.service-account-key }}
        project_id: ${{ inputs.project-id }}
    - name: Set Up Docker to Use gcloud Credentials
      run: gcloud auth configure-docker -q
    - run: docker build -t ${{ inputs.image-path }} -f ${{ inputs.dockerfile }} .
      shell: bash
    - run: docker push ${{ inputs.image-path }}
      shell: bash
    - id: get-image-digest	
      run: echo "::set-output name=image-digest::$(gcloud container images describe ${{ inputs.image-path }} --format='value(image_summary.digest)')"	
      shell: bash
