name: Biome Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        paths:
            - 'frontend/**'
defaults:
    run:
        working-directory: frontend            

jobs:
    check_biome:
        name: Checks Biome
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: frontend/package.json
                  cache: 'npm'
                  cache-dependency-path: frontend/package-lock.json
            - name: Install dependencies
              run: npm ci

