name: DAG - GRAPHQL_AHR_DATA (BEHAVIORAL_HEALTH)

on:
  workflow_dispatch:
  workflow_call:

env:
  WORKFLOW_ID: "GRAPHQL_AHR_DATA"
  DATASET_NAME: "graphql_ahr_data"
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  CATEGORY: "behavioral_health"
  AGE: "age"
  RACE_AND_ETHNICITY: "race_and_ethnicity"
  SEX: "sex"
  NATIONAL: "national"
  STATE: "state"
  AHR_API_KEY: ${{ secrets.AHR_API_KEY }}

jobs:
  trigger-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      # AGE NATIONAL
      - name: Process and write age national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          ahr_api_key: ${{ secrets.AHR_API_KEY }}

      # AGE STATE
      - name: Process and write age state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          ahr_api_key: ${{ secrets.AHR_API_KEY }}

      # RACE NATIONAL
      - name: Process and write race national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          ahr_api_key: ${{ secrets.AHR_API_KEY }}

      # RACE STATE
      - name: Process and write race state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          ahr_api_key: ${{ secrets.AHR_API_KEY }}

      # SEX NATIONAL
      - name: Process and write sex national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # SEX STATE
      - name: Process and write sex state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          ahr_api_key: ${{ secrets.AHR_API_KEY }}

      # EXPORTERS
      - name: Export age NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.AGE }}

      - name: Export race NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}

      - name: Export sex NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          category: ${{ env.CATEGORY }}
          demographic: ${{ env.SEX }}
          should_export_as_alls: "true"