name: DAG - ACS_CONDITION

# NOTE: This workflow requires pre-cached, ingested ACS files in our GCS landing buckets, (they have names like 2020-HEALTH_INSURANCE_BY_RACE_STATE_NHPI.json). If those files aren't present or might be out of date, please first run the dagAcsConditionPreCache.yml workflow, and then come back to run this workflow. Be mindful of rate limiting on the Census API.

on:
  workflow_dispatch:
  workflow_call:

env:
  WORKFLOW_ID: "ACS_CONDITION"
  DATASET_NAME: "acs_condition"
  GCS_LANDING_BUCKET: ${{ secrets.GCS_LANDING_BUCKET }} # files cached in runCacheAcsInGcsPipeline
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  RACE_AND_ETHNICITY: "race_and_ethnicity"
  AGE: "age"
  SEX: "sex"

jobs:
  # First process 2012 (OVERWRITE operation)
  process-2012:
    runs-on: ubuntu-latest
    steps:
      - name: Process and write to BigQuery 2012
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          year: "2012"
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

  # Process 2013-2017 concurrently (APPEND operations)
  process-2013-2017:
    needs: process-2012
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ["2013", "2014", "2015", "2016", "2017"]
      fail-fast: true
      max-parallel: 5
    steps:
      - name: Process and write to BigQuery ${{ matrix.year }}
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          year: ${{ matrix.year }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

  # Process 2018-2021 concurrently (APPEND operations)
  process-2018-2021:
    needs: process-2013-2017
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ["2018", "2019", "2020", "2021"]
      fail-fast: true
      max-parallel: 4
    steps:
      - name: Process and write to BigQuery ${{ matrix.year }}
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          year: ${{ matrix.year }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

  # Process 2022 separately (APPEND but also creates new tables)
  process-2022:
    needs: process-2018-2021
    runs-on: ubuntu-latest
    steps:
      - name: Process and write to BigQuery 2022
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          year: "2022"
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

  # Export demographic data - separate explicit jobs running in parallel
  export-race:
    needs: process-2022
    runs-on: ubuntu-latest
    steps:
      - name: Export data by race
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          should_export_as_alls: "true"

  export-age:
    needs: process-2022
    runs-on: ubuntu-latest
    steps:
      - name: Export data by age
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
          should_export_as_alls: "false"

  export-sex:
    needs: process-2022
    runs-on: ubuntu-latest
    steps:
      - name: Export data by sex
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          should_export_as_alls: "false"
