name: DAG - ACS_POPULATION

# NOTE: This workflow requires pre-cached, ingested ACS files in our GCS landing buckets, (they have names like 2009-HISPANIC_OR_LATINO_ORIGIN_BY_RACE_county.json). If those files aren't present or might be out of date, please first run the dagAcsPopulationPreCache.yml workflow, and then come back to run this workflow. Be mindful of rate limiting on the Census API; that single ingestion step repeats across all years.

on:
  workflow_dispatch:
  workflow_call:

env:
  WORKFLOW_ID: "ACS_POPULATION"
  DATASET_NAME: "acs_population"
  GCS_LANDING_BUCKET: ${{ secrets.GCS_LANDING_BUCKET }} # files cached in runCacheAcsInGcsPipeline
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}

jobs:
  process-export:
    runs-on: ubuntu-latest

    steps:

      # Process and write to BigQuery for each year
      - name: Process and write to BigQuery 2009
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2009"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2010
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2010"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2011
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2011"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2012
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2012"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2013
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2013"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2014
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2014"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2015
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2015"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2016
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2016"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2017
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2017"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2018
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2018"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2019
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2019"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2020
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2020"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2021
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2021"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write to BigQuery 2022
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          year: "2022"
          source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # Export from BQ to buckets
      - name: Export data by race
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: "race"
          should_export_as_alls: "true"

      - name: Export data by age
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: "age"

      - name: Export data by sex
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: "sex"