name: DAG - ACS_CONDITION

on:
  workflow_dispatch:
  workflow_call:

env:
  WORKFLOW_ID: "ACS_CONDITION"
  DATASET_NAME: "acs_condition"
  GCS_LANDING_BUCKET: ${{ secrets.GCS_LANDING_BUCKET }} # files cached in runCacheAcsInGcsPipeline
  INGESTION_SERVICE_URL: ${{ secrets.DATA_INGESTION_SERVICE_URL }}
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}

jobs:
  ingest-process-export:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Ingest data to GCS (Cache ACS source into tmp JSON in buckets)
      - name: Ingest ACS condition data 2012
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
        with:
          service_url: ${{ env.INGESTION_SERVICE_URL }}
          workflow_id: ${{ env.WORKFLOW_ID }}
          destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
          year: "2012"

      # - name: Ingest ACS condition data 2013
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2013"

      # - name: Ingest ACS condition data 2014
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2014"

      # - name: Ingest ACS condition data 2015
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2015"

      # - name: Ingest ACS condition data 2016
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2016"

      # - name: Ingest ACS condition data 2017
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2017"

      # - name: Ingest ACS condition data 2018
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2018"

      # - name: Ingest ACS condition data 2019
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2019"

      # - name: Ingest ACS condition data 2020
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2020"

      # - name: Ingest ACS condition data 2021
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2021"

      # - name: Ingest ACS condition data 2022
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runCacheAcsInGcsPipeline@main
      #   with:
      #     service_url: ${{ env.INGESTION_SERVICE_URL }}
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     destination_gcs_bucket: ${{ env.GCS_LANDING_BUCKET}}
      #     year: "2022"

      # # Step 2: Process and write to BigQuery
      # - name: Process and write to BigQuery 2012
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2012"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2013
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2013"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2014
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2014"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2015
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2015"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2016
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2016"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2017
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2017"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2018
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2018"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2019
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2019"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2020
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2020"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2021
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2021"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # - name: Process and write to BigQuery 2022
      #   uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
      #   with:
      #     workflow_id: ${{ env.WORKFLOW_ID }}
      #     dataset_name: ${{ env.DATASET_NAME }}
      #     source_gcs_bucket: ${{ env.GCS_LANDING_BUCKET }}
      #     year: "2022"
      #     service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # Step 3: Export from BQ to buckets
      - name: Export data by race
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: "race"
          should_export_as_alls: "true"

      - name: Export data by age
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: "age"

      - name: Export data by sex
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: "sex"