# .github/workflows/dagBjsIncarceration.yml
name: DAG - BJS_INCARCERATION_DATA
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag to checkout'
        type: string
        default: 'main'
env:
  WORKFLOW_ID: "BJS_INCARCERATION_DATA"
  DATASET_NAME: "bjs_incarceration_data"
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  RACE_AND_ETHNICITY: "race_and_ethnicity"
  AGE: "age"
  SEX: "sex"
jobs:
  trigger-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Process and write tables to BigQuery
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
      - name: Export race_and_ethnicity NDJSON files to GCS buckets from BigQuery tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          should_export_as_alls: "true"
      - name: Export age NDJSON files to GCS buckets from BigQuery tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
      - name: Export sex NDJSON files to GCS buckets from BigQuery tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}