name: DAG - CDC_RESTRICTED_DATA (COVID)
on:
  workflow_dispatch:
  workflow_call:
env:
  WORKFLOW_ID: "CDC_RESTRICTED_DATA"
  AGE_ADJUST_WORKFLOW_ID: "AGE_ADJUST_CDC_RESTRICTED"
  DATASET_NAME: "cdc_restricted_data"
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  GCS_MANUAL_UPLOADS_BUCKET: ${{ secrets.GCS_MANUAL_UPLOADS_BUCKET }}
  RACE_AND_ETHNICITY: "race_and_ethnicity"
  SEX: "sex"
  AGE: "age"
  COUNTY: "county"
  STATE: "state"
  NATIONAL: "national"
jobs:
  # Process sex data and export
  process-sex-data:
    runs-on: ubuntu-latest
    steps:
      - name: Process and write sex national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.NATIONAL }}
          demographic: ${{ env.SEX }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write sex state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.STATE }}
          demographic: ${{ env.SEX }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write sex county tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.COUNTY }}
          demographic: ${{ env.SEX }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          
      - name: Export sex data NDJSON files to GCS buckets
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          should_export_as_alls: "true"

  # Process age data and export
  process-age-data:
    runs-on: ubuntu-latest
    steps:
      - name: Process and write age national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.NATIONAL }}
          demographic: ${{ env.AGE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write age state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.STATE }}
          demographic: ${{ env.AGE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write age county tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.COUNTY }}
          demographic: ${{ env.AGE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          
      - name: Export age data NDJSON files to GCS buckets
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}

  # Process race data, run age adjust, and export
  process-race-data:
    runs-on: ubuntu-latest
    steps:
      - name: Process and write race national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.NATIONAL }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write race state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.STATE }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write race county tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          source_gcs_bucket: ${{ env.GCS_MANUAL_UPLOADS_BUCKET }}
          geographic: ${{ env.COUNTY }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          
      # Race-specific age adjustment step right before export
      - name: Run age adjustment for race data
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.AGE_ADJUST_WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          
      - name: Export race data NDJSON files to GCS buckets
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
