name: DAG - CDC_WISQARS_YOUTH_DATA (GUN DEATHS)
on:
  workflow_dispatch:
  workflow_call:
env:
  WORKFLOW_ID: "CDC_WISQARS_YOUTH_DATA"
  DATASET_NAME: "cdc_wisqars_youth_data"
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  RACE_AND_ETHNICITY: "race_and_ethnicity"
  NATIONAL: "national"
  STATE: "state"
jobs:
  trigger-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      # RACE NATIONAL
      - name: Process and write race and ethnicity national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # RACE STATE
      - name: Process and write race and ethnicity state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # EXPORTER
      - name: Export NDJSON files for race and ethnicity to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          should_export_as_alls: "true"