name: DAG - CDC_HIV_DATA
on:
  workflow_dispatch:
  workflow_call:
env:
  WORKFLOW_ID: "CDC_HIV_DATA"
  DATASET_NAME: "cdc_hiv_data"
  AGE_ADJUST_WORKFLOW_ID: "AGE_ADJUST_CDC_HIV"
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  RACE_AND_ETHNICITY: "race_and_ethnicity"
  SEX: "sex"
  AGE: "age"
  BLACK_WOMEN: "black_women"
  NATIONAL: "national"
  STATE: "state"
  COUNTY: "county"
jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      # BLACK WOMEN NATIONAL
      - name: Process and write black_women national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.BLACK_WOMEN }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # BLACK WOMEN STATE
      - name: Process and write black_women state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.BLACK_WOMEN }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # SEX NATIONAL
      - name: Process and write sex national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # SEX STATE
      - name: Process and write sex state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # SEX COUNTY
      - name: Process and write sex county tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # RACE NATIONAL
      - name: Process and write race national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # RACE STATE
      - name: Process and write race state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # RACE COUNTY
      - name: Process and write race county tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_AND_ETHNICITY }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # AGE NATIONAL
      - name: Process and write age national tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # AGE STATE
      - name: Process and write age state tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # AGE COUNTY
      - name: Process and write age county tables to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}


  age-adjust:
    runs-on: ubuntu-latest
    needs: [process-data]
    steps:
      - name: Process age adjustment for HIV data
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.AGE_ADJUST_WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

  export-race-and-age:
    runs-on: ubuntu-latest
    needs: [age-adjust]
    steps:
      - name: Export age-adjusted race NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: "race_and_ethnicity"

      - name: Export age NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}

  export-black-women-and-by-sex:
    runs-on: ubuntu-latest
    needs: [age-adjust]
    steps:
      - name: Export sex NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          should_export_as_alls: "true"

      - name: Export black_women NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.BLACK_WOMEN }}

