name: DAG - CENSUS_POP_ESTIMATES (RACE/SEX/AGE)
on:
  workflow_dispatch:
  workflow_call:
env:
  WORKFLOW_ID: "CENSUS_POP_ESTIMATES"
  DATASET_NAME: "census_pop_estimates"
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  RACE: "race"
jobs:
  trigger-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Process and write census population estimates to BigQuery
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runSourceToBqPipeline@main
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}
      - name: Export race NDJSON files to GCS buckets from BigQuery tables
        uses: SatcherInstitute/health-equity-tracker/.github/actions/runExportBqToGcsJsonPipeline@main
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE }}