name: DAG - MATERNAL_MORTALITY_DATA

on:
  workflow_dispatch:

jobs:
  trigger-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Process and write race tables to BigQuery
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: "MATERNAL_MORTALITY_DATA"
          dataset_name: "maternal_mortality_data"
          demographic: "race"
          service_url: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}

      - name: Export NDJSON files to GCS buckets from BigQuery tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ secrets.EXPORTER_SERVICE_URL }}
          dataset_name: "maternal_mortality_data"
          demographic: "race"
          should_export_as_alls: "true"
