name: DAG - PHRMA_DATA

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag to checkout'
        type: string
        default: 'main'

env:
  WORKFLOW_ID: "PHRMA_DATA"
  DATASET_NAME: "phrma_data"
  GCS_TO_BQ_SERVICE_URL: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
  EXPORTER_SERVICE_URL: ${{ secrets.EXPORTER_SERVICE_URL }}
  RACE_ETH: "race_and_ethnicity"
  AGE: "age"
  SEX: "sex"
  LIS: "lis"
  ELIGIBILITY: "eligibility"
  NATIONAL: "national"
  STATE: "state"
  COUNTY: "county"

jobs:
  trigger-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # NATIONAL LEVEL PROCESSING
      # Process and write tables to BigQuery for each demographic at national level
      - name: Process and write race tables to BigQuery (national)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_ETH }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write age tables to BigQuery (national)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write sex tables to BigQuery (national)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write lis tables to BigQuery (national)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.LIS }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write eligibility tables to BigQuery (national)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.ELIGIBILITY }}
          geographic: ${{ env.NATIONAL }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # STATE LEVEL PROCESSING
      # Process and write tables to BigQuery for each demographic at state level
      - name: Process and write race tables to BigQuery (state)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_ETH }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write age tables to BigQuery (state)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write sex tables to BigQuery (state)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write lis tables to BigQuery (state)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.LIS }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write eligibility tables to BigQuery (state)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.ELIGIBILITY }}
          geographic: ${{ env.STATE }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # COUNTY LEVEL PROCESSING
      # Process and write tables to BigQuery for each demographic at county level
      - name: Process and write race tables to BigQuery (county)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_ETH }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write age tables to BigQuery (county)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write sex tables to BigQuery (county)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write lis tables to BigQuery (county)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.LIS }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      - name: Process and write eligibility tables to BigQuery (county)
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.ELIGIBILITY }}
          geographic: ${{ env.COUNTY }}
          service_url: ${{ env.GCS_TO_BQ_SERVICE_URL }}

      # EXPORT OPERATIONS
      # Export NDJSON files to GCS buckets for each demographic breakdown
      - name: Export NDJSON files to GCS buckets from race tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE_ETH }}

      - name: Export NDJSON files to GCS buckets from age tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.AGE }}

      - name: Export NDJSON files to GCS buckets from sex tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.SEX }}
          should_export_as_alls: "true"

      - name: Export NDJSON files to GCS buckets from lis tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.LIS }}

      - name: Export NDJSON files to GCS buckets from eligibility tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ env.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.ELIGIBILITY }}