name: DEPLOY MAIN CODE TO INFRA-TEST GCP (DEV SITE)

on:
  push:
    branches: [main]
    paths:
      # Run only if data pipeline services or the frontend/ changes
      - 'config/**'
      - 'data/**'
      - 'data_server/**'
      - 'e2e_tests/**'
      - 'exporter/**'
      - 'frontend_server/**'
      - 'python/**'
      - 'requirements/**'
      - 'run_gcs_to_bq/**'
      - 'run_ingestion/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'SatcherInstitute/health-equity-tracker'
    name: Deploy to infra-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Deploy
        uses: ./.github/actions/buildAllAndDeploy
        with:
          ref: main
          environment: dev
          deployer-sa-key: ${{ secrets.TEST_DEPLOYER_SA_KEY }}
          project-id: ${{ secrets.TEST_PROJECT_ID }}
          tf-state-bucket: ${{ secrets.TEST_TF_STATE_BUCKET }}
          ahr-api-key: ${{ secrets.AHR_API_KEY }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
