name: Deploy to Dev

on:
  push:
      branches: [master, e2e-test]
  workflow_dispatch:

jobs:
  deploy:
    name: Build Images and Deploy to Dev Environment
    runs-on: ubuntu-latest

    steps: 
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set Up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.DEV_DEPLOYER_SA_KEY }}
          project_id: ${{ secrets.DEV_PROJECT_ID }}
          export_default_credentials: true
      - name: Set Up Docker to Use gcloud Credentials
        run: gcloud auth configure-docker -q
      - name: Build and Push Data Serving Image
        id: serving
        uses: ./.github/actions/buildAndPush
        with:
          dockerfile: 'data_server/Dockerfile'
          image-path: 'gcr.io/${{ secrets.DEV_PROJECT_ID }}/data-server-service-automated'
      - name: Build and Push Data Ingestion Image
        id: ingestion
        uses: ./.github/actions/buildAndPush
        with:
          dockerfile: 'run_ingestion/Dockerfile'
          image-path: 'gcr.io/${{ secrets.DEV_PROJECT_ID }}/ingestion-service-automated'  
      - name: Build and Push GCS to BQ Image
        id: gcstobq
        uses: ./.github/actions/buildAndPush
        with:
          dockerfile: 'run_gcs_to_bq/Dockerfile'
          image-path: 'gcr.io/${{ secrets.DEV_PROJECT_ID }}/gcs-to-bq-service-automated'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Save credentials
        working-directory: ./config
        run: |
          echo ${{ secrets.DEV_TF_STATE_BUCKET }}
          cat > creds.json << EOF 
          ${{ secrets.DEV_DEPLOYER_SA_KEY }}
          EOF
      - name: Terraform Init
        working-directory: ./config
        run: | 
          terraform init -backend-config="bucket=jenniebrown-tf-state" \
          -backend-config="credentials=creds.json"
      - name: Terraform Format
        working-directory: ./config
        run: terraform fmt -check
      - name: Terraform Apply
        #if: github.ref == 'refs/heads/$default-branch' && github.event_name == 'push'
        id: terraform
        working-directory: ./config
        run: |
          terraform apply -auto-approve -var-file=test/jennie.tfvars \
          -var 'gcp_credentials=${{ secrets.DEV_DEPLOYER_SA_KEY }}' \
          -var 'project_id=${{ secrets.DEV_PROJECT_ID }}' \
          -var 'ingestion_image_digest=${{ steps.ingestion.outputs.image-digest }}' \
          -var 'gcs_to_bq_image_digest=${{ steps.gcstobq.outputs.image-digest }}' \
          -var 'data_server_image_digest=${{ steps.serving.outputs.image-digest }}'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run E2E Tests
        run: |
          pip install -r integration_tests/requirements.txt
          echo ${{ steps.terraform.outputs.data_server_url }}
          python integration_tests/data_serving.py || code=$?; if [[ $code -ne 0 ]]; then exit $code; fi
        env:
          SERVICE_URL: ${{ steps.terraform.outputs.data_server_url }}
        
