name: TEST CHANGES

on:
  push:
    branches: [main, infra-test]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 2
      - name: Get changes
        id: git_diff
        run: |
          diff_output=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} \
            -- 'airflow/' 'config/' 'data/' 'data_server/' \
            'e2e_tests/' 'exporter/' 'frontend_server/' \
            'python/' 'requirements/' 'run_gcs_to_bq/' 'run_ingestion/')
          echo "::set-output name=diff_output::$diff_output"

      - name: Check if diff exists
        id: check_diff
        run: |
          if [ -n "${{ steps.git_diff.outputs.diff_output }}" ]; then
            echo "Diff exists"
            echo "::set-output name=diff_exists::true"
          else
            echo "No diff exists"
            echo "::set-output name=diff_exists::false"
          fi

      - name: Use the diff status
        run: |
          if [ "${{ steps.check_diff.outputs.diff_exists }}" = "true" ]; then
            echo "There are changes in pipeline folders"
          else
            echo "No changes in pipeline folders"
          fi
