name: Check Changes

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changed files
        id: check_files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changed_files::$changed_files"

      - name: Analyze changes
        run: |
          changed_files="$INPUT_CHANGED_FILES"
          if [[ -z "$changed_files" ]]; then
            echo "No changed files detected."
            exit 1
          fi

          pipeline_folders=("airflow" "config" "data" "data_server" "e2e_tests" "exporter" "frontend_server" "python" "requirements" "run_gcs_to_bq" "run_ingestion")
          frontend_changed=$(echo "$changed_files" | grep -E '^frontend/' || true)
          pipeline_changed=$(echo "$changed_files" | grep -E "^(${pipeline_folders[*]})/" || true)

          if [[ -n "$pipeline_changed" ]]; then
            echo "commit contains at least one changed file within pipeline folders:"
            echo "$pipeline_changed"
          elif [[ -n "$frontend_changed" ]]; then
            echo "commit contains at least one changed file in the frontend/ folder, and does not include files changed within the pipeline folders:"
            echo "$frontend_changed"
          else
            echo "commit doesn't include any files changed within frontend/ nor pipeline folders"
          fi
