name: Keep `release` branch synced to latest GitHub release tag
on:
  push:
    tags:
      - "ReleaseV*"

jobs:
  deploy_releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release

      # Debugging: Print the tag name
      - name: Debug GitHub variables
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

      # Point release branch at the latest tag so Netlify can deploy it
      - name: Point release branch at tag
        run: |
          echo "Setting 'release' branch to 'tags/${GITHUB_REF_NAME}'"
          git checkout release
          git reset --hard "tags/${GITHUB_REF_NAME}"
          git push -f
