name: Format Python Files with Black

on:
  pull_request:
    paths:
      - '**/*.py' # Trigger only on Python files

jobs:
  format:
    name: Format with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install black

      - name: Format changed Python files
        run: |
          git diff --name-only $GITHUB_BASE_REF -- $GITHUB_HEAD_REF | grep '\.py$' | xargs black

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "info@healthequitytracker.org"
          git add .
          git commit -m "Auto-format Python files using Black" || echo "No changes to commit"
