name: 'Check spelling on changed files'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: 'cspell.config.json'
