# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check Outgoing Links
on:
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 1PM UTC (9AM EST)
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests with Node.js 16.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.0
    - run: npm install
    - run: npm run build
    - run: npm run url
